apiVersion: v1
entries:
  oao-platform:
  - annotations:
      artifacthub.io/license: MIT
      artifacthub.io/links: |
        - name: Documentation
          url: https://thfai2000.github.io/open-agent-orchestra/
        - name: Source
          url: https://github.com/thfai2000/open-agent-orchestra
    apiVersion: v2
    appVersion: 1.30.11
    created: "2026-04-25T06:38:14.292862719Z"
    description: Open Agent Orchestra (OAO) — Autonomous AI workflow engine (API +
      UI + PostgreSQL)
    digest: be8eadb3b21c7ac75bc834b7386a8311f3e59958671ca5e44a2649000a63fa1f
    home: https://github.com/thfai2000/open-agent-orchestra
    keywords:
    - ai
    - agents
    - workflow
    - copilot
    - orchestration
    maintainers:
    - name: thfai2000
      url: https://github.com/thfai2000
    name: oao-platform
    sources:
    - https://github.com/thfai2000/open-agent-orchestra
    type: application
    urls:
    - https://thfai2000.github.io/open-agent-orchestra/charts/oao-platform-1.30.11.tgz
    version: 1.30.11
generated: "2026-04-25T06:38:14.292390391Z"
