apiVersion: v1
entries:
  oao-platform:
  - annotations:
      artifacthub.io/license: MIT
      artifacthub.io/links: |
        - name: Documentation
          url: https://thfai2000.github.io/open-agent-orchestra/
        - name: Source
          url: https://github.com/thfai2000/open-agent-orchestra
    apiVersion: v2
    appVersion: 1.6.0
    created: "2026-04-20T16:57:34.456760295Z"
    description: Open Agent Orchestra (OAO) — Autonomous AI workflow engine (API +
      UI + PostgreSQL)
    digest: 0a8c94b02de3b8912b59cf61de3a0646c5f47b43bf19c52bb7c9ee49d2baa748
    home: https://github.com/thfai2000/open-agent-orchestra
    keywords:
    - ai
    - agents
    - workflow
    - copilot
    - orchestration
    maintainers:
    - name: thfai2000
      url: https://github.com/thfai2000
    name: oao-platform
    sources:
    - https://github.com/thfai2000/open-agent-orchestra
    type: application
    urls:
    - https://thfai2000.github.io/open-agent-orchestra/charts/oao-platform-1.6.0.tgz
    version: 1.6.0
generated: "2026-04-20T16:57:34.456287124Z"
