apiVersion: v1
entries:
  oao-platform:
  - annotations:
      artifacthub.io/license: MIT
      artifacthub.io/links: |
        - name: Documentation
          url: https://thfai2000.github.io/open-agent-orchestra/
        - name: Source
          url: https://github.com/thfai2000/open-agent-orchestra
    apiVersion: v2
    appVersion: 1.30.11
    created: "2026-04-23T17:21:32.147021254Z"
    description: Open Agent Orchestra (OAO) — Autonomous AI workflow engine (API +
      UI + PostgreSQL)
    digest: 72b0acdbc7fe61a024ae7fa6716e0fe36d7a991a24277d80232945ced5b22203
    home: https://github.com/thfai2000/open-agent-orchestra
    keywords:
    - ai
    - agents
    - workflow
    - copilot
    - orchestration
    maintainers:
    - name: thfai2000
      url: https://github.com/thfai2000
    name: oao-platform
    sources:
    - https://github.com/thfai2000/open-agent-orchestra
    type: application
    urls:
    - https://thfai2000.github.io/open-agent-orchestra/charts/oao-platform-1.30.11.tgz
    version: 1.30.11
generated: "2026-04-23T17:21:32.146627561Z"
